Features/form travel
Flora-J/BeMyGuide pull request #2
Opened 2022-12-01 10:48 UTC by Flora-J

2022-12-02 08:14 UTC, tibz7884 commented on lib/views/form_travel_view.dart
> +  indifferent
Peut etre non-binaire

2022-12-02 08:16 UTC, tibz7884 commented on lib/views/form_travel_view.dart
> +      String formattedDate = DateFormat('dd/MM/yyy').format(currentDate);
Reformater la date au format France dd/mmm/yyyy

2022-12-02 08:17 UTC, tibz7884 requested changes
A voir concernant l'accessibilité du calendrier

2022-12-05 13:14 UTC, ClaireMath commented
Seems good to me.

2022-12-05 13:15 UTC, ClaireMath commented on lib/views/form_travel_view.dart
> +  indifferent
oui je suis d'accord, vaudrait mieux changer pour la sensibilité des gens

2022-12-05 13:18 UTC, ClaireMath approved these changes
Seems good to me

2022-12-06 10:14 UTC, tibz7884 approved these changes

2023-01-17 10:54 UTC, merged